name:                animalclub
version:             0.1.0.0
github:              "pdlla/animalclub"
license:             BSD3
author:              "Peter Lu"
maintainer:          "chippermonky@gmail.com"
copyright:           "2018 Peter Lu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/pdlla/animalclub#readme>


ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
#- -Werror

default-extensions:
- InstanceSigs
- LambdaCase
- OverloadedStrings
- GADTs
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- FlexibleInstances
- FlexibleContexts
- ScopedTypeVariables
- MultiWayIf
- TupleSections
- MultiParamTypeClasses

dependencies:
- base >= 4.7 && < 5
- vector
- MonadRandom
- random
- mwc-random
- mtl
- QuickCheck
- array
- text
- linear
- microlens-platform
- adjunctions
- containers
- deepseq
- primitive
- monad-parallel
- parallel

library:
  source-dirs: src
  exposed-modules:
    # Genetics
    - AnimalClub.Genetics
    - AnimalClub.Genetics.DNA
    - AnimalClub.Genetics.Gene
    #- AnimalClub.Genetics.Genotype
    # Skellygen
    - AnimalClub.Skellygen
    - AnimalClub.Skellygen.Math.Hierarchical
    - AnimalClub.Skellygen.Math.Mesh
    - AnimalClub.Skellygen.Math.Quaternion
    # Animal
    - AnimalClub.Animals
    - AnimalClub.Animals.Worm

  dependencies:


executables:
  genetics:
    main:                genetics.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - animalclub

  goat:
    main:                goat.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    other-modules:
    - Animals
    dependencies:
    - animalclub

#+RTS -sstderr -RTS
  wormbreeder:
    main:                wormbreeder.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - animalclub

benchmarks:
  genetics-benchmarks:
    source-dirs: benchmark
    main: performance_test.hs
    dependencies:
    - animalclub
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N


tests:
  genetics-test:
    main:                tests_genetics.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - animalclub

  skellygen-test:
    main:                tests_skellygen.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - animalclub
